spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin
      database: customerdb
      authentication-database: admin

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
